import { Company } from "@/lib/types";

export const companies: Company[] = [
  {
    id: "c1",
    external_place_id: "mock-place-1",
    company_name: "Blue River Dental Group",
    website_url: "https://www.blueriverdental.example",
    website_status: "verified",
    main_phone: "(312) 555-0101",
    formatted_address: "101 Main St, Chicago, IL 60601",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    latitude: 41.8864,
    longitude: -87.6186,
    primary_category: "Dental Clinic",
    pipeline_stage: "qualified",
    notes: "High review score and multiple locations.",
    last_touched_at: "2026-01-10T10:00:00Z",
    next_follow_up_at: "2026-01-17T10:00:00Z",
    primary_draft: "",
    outreach_draft_status: "not_started",
    outreach_send_status: "not_contacted",
    first_contacted_at: null,
    follow_up_due_at: "2026-01-17T10:00:00Z",
    stop_reason: null,
    next_recommended_action: "Advance deal and propose next step",
    created_at: "2026-01-03T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "c2",
    external_place_id: "mock-place-2",
    company_name: "Northwind HVAC Services",
    website_url: "https://www.northwindhvac.example",
    website_status: "likely",
    main_phone: "(773) 555-0144",
    formatted_address: "22 Market Ave, Chicago, IL 60607",
    city: "Chicago",
    state: "IL",
    zip: "60607",
    latitude: 41.8757,
    longitude: -87.6544,
    primary_category: "HVAC Contractor",
    pipeline_stage: "website_verified",
    notes: "Website likely match, still needs phone confirmation.",
    last_touched_at: "2026-01-10T10:00:00Z",
    next_follow_up_at: null,
    primary_draft: "",
    outreach_draft_status: "not_started",
    outreach_send_status: "not_contacted",
    first_contacted_at: null,
    follow_up_due_at: null,
    stop_reason: null,
    next_recommended_action: "Run contact discovery",
    created_at: "2026-01-04T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "c3",
    external_place_id: "mock-place-3",
    company_name: "Maple Grove Law Office",
    website_url: "",
    website_status: "missing",
    main_phone: "(847) 555-0198",
    formatted_address: "890 State St, Evanston, IL 60201",
    city: "Evanston",
    state: "IL",
    zip: "60201",
    latitude: 42.0451,
    longitude: -87.6877,
    primary_category: "Law Firm",
    pipeline_stage: "new",
    notes: "No clear official website yet.",
    last_touched_at: "2026-01-12T10:00:00Z",
    next_follow_up_at: null,
    primary_draft: "",
    outreach_draft_status: "not_started",
    outreach_send_status: "not_contacted",
    first_contacted_at: null,
    follow_up_due_at: null,
    stop_reason: null,
    next_recommended_action: "Verify official website",
    created_at: "2026-01-06T10:00:00Z",
    updated_at: "2026-01-12T10:00:00Z",
  },
];
